### PR TITLE
Fix wrong CSI driver name reference

### LINKED ISSUE #273: Fix wrong CSI driver name reference
**Describe the bug**

We are checking for the wrong CSI driver name in the MCM: https://github.com/ironcore-dev/machine-controller-manager-provider-ironcore/blob/main/pkg/ironcore/get_volume_ids.go#L26

We should use here the correct CSI driver name as defined in the CSI project: https://github.com/ironcore-dev/ironcore-csi-driver/blob/main/pkg/driver/constants.go#L48

### PR DESCRIPTION
**Pull request by ushabelgur**
# Proposed Changes

- Fix wrong CSI driver name reference

Fixes #273

### CODE REVIEW

**Comment by afritzler** [comment]
We should add a flag to override the default value `csi.ironcore.dev` to ensure backward compatibility.

File: pkg/ironcore/get_volume_ids.go [hunk 1]
```diff
@@ -46,3 +47,7 @@ func (d *ironcoreDriver) GetVolumeIDs(_ context.Context, req *driver.GetVolumeID
 	}
 	return response, nil
 }
+
+func AddCsiDriverFlag(fs *pflag.FlagSet) {
```
Comment (afritzler) [inline pkg/ironcore/get_volume_ids.go:51]: Can we move this flag parsing to the `AddExtraFlags` method please.

File: pkg/ironcore/get_volume_ids.go [hunk 2]
```diff
@@ -18,12 +18,13 @@ import (
...
 
 	"github.com/gardener/machine-controller-manager/pkg/util/provider/driver"
+	"github.com/spf13/pflag"
 	"k8s.io/klog/v2"
 )
 
 // IronCoreCSIDriver is the CSI driver for ironcore provisioner
-const (
-	IroncoreCSIDriver = "ironcore-csi-driver"
+var (
```
Comment (afritzler) [inline pkg/ironcore/get_volume_ids.go:26]: Please move this var to the `cmd/main.go` where the other flags are located.

**Review by afritzler — CHANGES_REQUESTED** [review]

File: pkg/ironcore/get_volume_ids.go (hunk 2 above)
Comment (ushabelgur) [reply pkg/ironcore/get_volume_ids.go:26]: If I move this variable to main.go I will have to update ironcoreDriver structure and pass csi driver name via this struct.
So that GetVolumeIDs method can access it. Is that ok ?

Comment (afritzler) [reply pkg/ironcore/get_volume_ids.go:26]: That is correct. But that is the cleaner approach by having flags at a central place and pass them on to where they are needed.

Comment (afritzler) [reply pkg/ironcore/get_volume_ids.go:26]: Also can we call the `var` `CSIDriver` name. No need to prefix it.

**Review by afritzler — CHANGES_REQUESTED** [review]

File: pkg/ironcore/driver.go [hunk 3]
```diff
@@ -39,13 +39,15 @@ type ironcoreDriver struct {
...
+	IroncoreCSIDriver string
 }
 
 // NewDriver returns a new Gardener ironcore driver object
-func NewDriver(c client.Client, namespace string) driver.Driver {
+func NewDriver(c client.Client, namespace, csiDriver string) driver.Driver {
 	return &ironcoreDriver{
 		IroncoreClient:    c,
 		IroncoreNamespace: namespace,
+		IroncoreCSIDriver: csiDriver,
```
[the remark this answers is not in the document]
Comment (ushabelgur) [reply pkg/ironcore/driver.go]: Done

File: pkg/ironcore/get_volume_ids_test.go [hunk 4]
```diff
@@ -25,7 +25,7 @@ var _ = Describe("GetVolumeIDs", func() {
 
 	It("should get volume IDs", func(ctx SpecContext) {
 		By("giving correct driver name")
-		csiDriverName := IroncoreCSIDriver
+		csiDriverName := "csi.ironcore.dev"
```
[the remark this answers is not in the document]
Comment (ushabelgur) [reply pkg/ironcore/get_volume_ids_test.go]: Done

File: cmd/machine-controller/main.go [hunk 5]
```diff
@@ -114,4 +115,5 @@ func getIroncoreClientAndNamespace() (client.Client, string, error) {
 
 func AddExtraFlags(fs *pflag.FlagSet) {
 	fs.StringVar(&IroncoreKubeconfigPath, "ironcore-kubeconfig", "", "Path to the ironcore kubeconfig.")
+	fs.StringVar(&CSIDriver, "csi.ironcore.dev", "", "CSI driver for ironcore provisioner.")
```
[the remark this answers is not in the document]
Comment (ushabelgur) [reply cmd/machine-controller/main.go]: Done

File: pkg/ironcore/get_volume_ids.go (hunk 2 above)
Comment (ushabelgur) [reply pkg/ironcore/get_volume_ids.go]: Done

File: cmd/machine-controller/main.go [hunk 6]
```diff
@@ -39,6 +39,7 @@ import (
 
 var (
 	IroncoreKubeconfigPath string
+	CSIDriver              string
```
[the remark this answers is not in the document]
Comment (ushabelgur) [reply cmd/machine-controller/main.go]: Done

**Review by afritzler — APPROVED** [review]
